### PR TITLE
Switch to docker compose using testbed CA certificates

### PR DESCRIPTION
**Pull request by jfernandezsqs**
The updates included in this PR are a major change to the IDS-testbed repository.
It has been taken into account the previous PR already included in the IDS-testbed master branch.

Changes included:
- Deleted source repositories.
- Added DAPS, DSC and MDB folders.
- Added `docker-compose.yml` file.
- `InstallationGuide.md` documentation update for the automatic set up of the testbed.

### CODE REVIEW

**Comment by jfernandezsqs** [comment]
This PR #71 resolves issue #57.

@sebplorenz  I have also taken into account the latest documentation updates detailed [here](https://github.com/International-Data-Spaces-Association/IDS-testbed/pull/62/commits/4da729327ca4f9f301bd371617bc8e23c49bb6e2)

**Comment by sebplorenz** [comment]
All my commits gone?

**Comment by jfernandezsqs** [comment]
> All my commits gone?

I have used your proposed solution #62 @sebplorenz, including the latest documentation update that is detailed there.
As discussed in the SubWG Testbed meeting I have changed the certificates used with the ones that are included in the IDS-testbed CA.

**Comment by sebplorenz** [comment]
@jfernandezsqs The problem is, I cannot see the changes between my original branch and yours, to see what you actually did. Therefore I copied my branch into this repo: https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/feature/57_using_docker_compose
Can you please do your changes on this branch again and replace this pull request?

**Comment by jfernandezsqs** [comment]
> @jfernandezsqs The problem is, I cannot see the changes between my original branch and yours, to see what you actually did. Therefore I copied my branch into this repo: https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/feature/57_using_docker_compose Can you please do your changes on this branch again and replace this pull request?

I have made the changes on the specified [branch](https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/feature/57_using_docker_compose) and for claritication I created another pull request #72 with the changes.
If there are no objections I will close this pull request and leave the other open.

**Pull request closed without merging**
