### PR TITLE
Adding GitBook Configuration files

### PR DESCRIPTION
**Pull request by ssteinbuss**
As described in #116 the rendering to GitBook should be improved. To do so, the GitBook Configuration files need to be added first. 

Adding the Gitbook configuration files:

* adding .gitbook.yaml as config starter
* Adding SUMMARY.MD with TOC structure

The structure in SUMMARY.MD is a proposal, please indicate if changes are requested.

### CODE REVIEW

**Comment by jfernandezsqs** [comment]
Please  include at the `SUMMARY.md` file the `Testsuite` folder.

**Comment by jfernandezsqs** [comment]
I have added the Testsuite to the `SUMMARY.md` file
Let me know @ssteinbuss if it looks fine for you.

**Comment by ssteinbuss** [comment]
> I have added the Testsuite to the `SUMMARY.md` file Let me know @ssteinbuss if it looks fine for you.

Fixed the link. The markdown file needs to be referenced directly, not only the folder. Looks good now.

**Comment by ssteinbuss** [comment]
@jfernandezsqs and @Sonia-IDSA could you approve this PR?

**Review by jfernandezsqs — APPROVED** [review]
Looks good to me.

**Review by Sonia-IDSA — COMMENTED** [review]
Why do we only show the CA under "Details on IDS Reference Testbed Components"?

**Pull request merged**
