### PR TITLE
Re-added option for signing existing public keys, removed pycache

### PR DESCRIPTION
**Pull request by mohuber**
during the restructuring of the repo the newly added option for signing existing public keys were lost. I have readded it now.
Additionally, I have removed the pycache folder from the repo since it is not necessary to share it.

### CODE REVIEW

**Comment by mohuber** [comment]
making the python files directly executable in the CertificateAuthority-Repo is not necessary, we can simply run them with "python3 file.py"

**Comment by mohuber** [comment]
@aitorce could you please add the .serial for the root CA and the subCA to the respective "CertificateAuthority/data/" folders? Without them, no new certificates can be signed.

**Review by aitorce — APPROVED** [review]
The proposed changes look good. Approved.

The .serial files have been added in new PRs @mohuber

**Review by Sonia-IDSA — APPROVED** [review]
changes are ok

**Pull request merged**
