### PR TITLE
Updating the MVDS Visual

### PR DESCRIPTION
**Pull request by anilturkmayali**
Changed the MVDS visual, by replacing one connector's role as Data Consumer.

The issue was originally raised here: https://github.com/International-Data-Spaces-Association/idsa/issues/129

### CODE REVIEW

**Comment by jfernandezsqs** [comment]
This [picture](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/MVDS-Visual-Update/pictures/MVDS-Testbed_1.0.png) is wrong.
It should be `Connector B (acting as Data Consumer)` and `Connector A (acting as Data Provider)`

Also, line 33 of the README.md file should be changed accordingly.
Wrong --> `first_version`
Correct --> `first_version`

**Comment by anilturkmayali** [comment]
> This [picture](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/MVDS-Visual-Update/pictures/MVDS-Testbed_1.0.png) is wrong. It should be `Connector B (acting as Data Consumer)` and `Connector A (acting as Data Provider)`
> 
> Also, line 33 of the README.md file should be changed accordingly. Wrong --> `first_version` Correct --> `first_version`

Thank you for the feedback @jfernandezsqs the changes are reflected in the updated branch.

**Review by jfernandezsqs — APPROVED** [review]
Changes correctly applied.

**Review by Sonia-IDSA — APPROVED** [review]
changes ok

**Pull request merged**
